
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const AnomalyPage = lazy(() => import("./pages/AnomalyPage.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const VisualizationPage = lazy(() => import("./pages/VisualizationPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/anomaly-page", element: <AnomalyPage />},
	{ path: "/anomalypage", element: <AnomalyPage />},
	{ path: "/", element: <App />},
	{ path: "/visualization-page", element: <VisualizationPage />},
	{ path: "/visualizationpage", element: <VisualizationPage />},

];
